version: "3.9"

services:
  db:
    image: postgres:16
    container_name: auth_db
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  auth-service:
    build: .
    container_name: auth_service
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://auth_user:auth_pass@db:5432/auth_db
      JWT_PRIVATE_KEY_PATH: /app/keys/private.pem
      JWT_PUBLIC_KEY_PATH: /app/keys/public.pem
      JWT_ALGORITHM: RS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 30
    ports:
      - "8000:8000"
    volumes:
      - ./keys:/app/keys  # mount keys if you have them locally

volumes:
  db_data: